export const dataSource = [
  {
    key: '1',
    badgeId: '50345',
    transactionId: '...ufnn8801',
    deviceCode: '7XSH9',
    overallDevice:'',
    punchResponse:'',
    punchTime:'',
  },
  {
    key: '2',
    badgeId: '50346',
    transactionId: '...ufnn8802',
    deviceCode: 'FH6SC',
    overallDevice:'',
    punchResponse:'',
    punchTime:'',
    createdDateTime:''
  },
  {
    key: '3',
    badgeId: '50347',
    transactionId: '...ufnn8803',
    deviceCode: 'GHC54',
    overallDevice:'',
    punchResponse:'',
    punchTime:'',
    createdDateTime:''
  },
  {
    key: '4',
    badgeId: '50345',
    transactionId: '...ufnn8801',
    deviceCode: '7XSH9',
    overallDevice:'',
    punchResponse:'',
    punchTime:'',
  },
  {
    key: '5',
    badgeId: '50346',
    transactionId: '...ufnn8802',
    deviceCode: 'FH6SC',
    overallDevice:'',
    punchResponse:'',
    punchTime:'',
    createdDateTime:''
  },
  {
    key: '6',
    badgeId: '50347',
    transactionId: '...ufnn8803',
    deviceCode: 'GHC54',
    overallDevice:'',
    punchResponse:'',
    punchTime:'',
    createdDateTime:''
  },
  {
    key: '7',
    badgeId: '50345',
    transactionId: '...ufnn8801',
    deviceCode: '7XSH9',
    overallDevice:'',
    punchResponse:'',
    punchTime:'',
  },
  {
    key: '8',
    badgeId: '50346',
    transactionId: '...ufnn8802',
    deviceCode: 'FH6SC',
    overallDevice:'',
    punchResponse:'',
    punchTime:'',
    createdDateTime:''
  },
  {
    key: '9',
    badgeId: '50347',
    transactionId: '...ufnn8803',
    deviceCode: 'GHC54',
    overallDevice:'',
    punchResponse:'',
    punchTime:'',
    createdDateTime:''
  },
  {
    key: '10',
    badgeId: '50345',
    transactionId: '...ufnn8801',
    deviceCode: '7XSH9',
    overallDevice:'',
    punchResponse:'',
    punchTime:'',
  },
  {
    key: '11',
    badgeId: '50346',
    transactionId: '...ufnn8802',
    deviceCode: 'FH6SC',
    overallDevice:'',
    punchResponse:'',
    punchTime:'',
    createdDateTime:''
  },
  {
    key: '12',
    badgeId: '50347',
    transactionId: '...ufnn8803',
    deviceCode: 'GHC54',
    overallDevice:'',
    punchResponse:'',
    punchTime:'',
    createdDateTime:''
  },
]