import icon from '../../../image/ModelA.png';
export const activityLogs = [
  {
    key: '1',
    coulmnIcon: icon,
    activityId: 1,
    eventType: 'Connection Update',
    logDate: new Date(),
    users: 'aarthi@oloid.com',
    connection:'Connection ABC',
    application:'Application ABC',
    source: 'API',
    description:'Update a User',
    endpointName:'Tablet #2',
    endpointId:'DF34DS',
    location:'Milpitas, Bld 14',
    facialRecognitionModel: 'Model A'
  },
  {
    key: '2',
    coulmnIcon: icon,
    activityId: 2,
    eventType: 'User Update',
    logDate: new Date(),
    users: 'atashi@oloid.com',
    connection:'Connection ABC',
    application:'Application ABC',
    source: 'Web Portal'
  },
  {
    key: '3',
    coulmnIcon: icon,
    activityId: 3,
    eventType: 'Connection Update',
    logDate: new Date(),
    users: 'madhu@oloid.com',
    connection:'Connection ABC',
    application:'Application ABC',
    source: 'Endpoint'
  },
  {
    key: '4',
    coulmnIcon: icon,
    activityId: 4,
    eventType: 'User Update',
    logDate: new Date(),
    users: 'aarthi@oloid.com',
    connection:'Connection ABC',
    application:'Application ABC',
    source: 'Endpoint'
  },
  {
    key: '5',
    coulmnIcon: icon,    activityId: 5,
    eventType: 'Application Update',
    logDate: new Date(),
    users: 'atashi@oloid.com',
    connection:'Connection ABC',
    application:'Application ABC',
    source: 'Web Portal'
  },
  {
    key: '6',
    coulmnIcon: icon,    activityId: 6,
    eventType: 'User Update',
    logDate: new Date(),
    users: 'madhu@oloid.com',
    connection:'Connection ABC',
    application:'Application ABC',
    source: 'API',
  },
  {
    key: '7',
    coulmnIcon: icon,
    activityId: 7,
    eventType: 'Connection Update',
    logDate: new Date(),
    users: 'aarthi@oloid.com',
    connection:'Connection ABC',
    application:'Application ABC',
    source: 'Endpoint'
  },
  {
    key: '8',
    coulmnIcon: icon,
    activityId: 8,
    eventType: 'User Update',
    logDate: new Date(),
    users: 'atashi@oloid.com',
    connection:'Connection ABC',
    application:'Application ABC',
    source: 'Web Portal'
  },
  {
    key: '9',
    coulmnIcon: icon,
    activityId: 90,
    eventType: 'Application Update',
    logDate: new Date(),
    users: 'madhu@oloid.com',
    connection:'Connection ABC',
    application:'Application ABC',
    source: 'Endpoint'
  },
  {
    key: '10',
    coulmnIcon: icon,
    activityId: 10,
    eventType: 'User Update',
    logDate: new Date(),
    users: 'aarthi@oloid.com',
    connection:'Connection ABC',
    application:'Application ABC',
    source: 'API',
  },
  {
    key: '11',
    coulmnIcon: icon,
    activityId: 'aarthi@oloid.com',
    eventType: 'Application Update',
    logDate: new Date(),
    users: 'atashi@oloid.com',
    connection:'Connection ABC',
    application:'Application ABC',
    source: 'Web Portal'
  },
  {
    key: '12',
    coulmnIcon: icon,
    activityId: 17,
    eventType: 'Application Update',
    logDate: new Date(),
    users: 'aarthi@oloid.com',
    connection:'Connection ABC',
    application:'Application ABC',
    source: 'Endpoint'
  },
]