import icon from '../../../image/user_preview.png';
export const dataSource = [
  {
    key: '1',
    userId: 1,
    faces: icon,
    TransactionDate:'May 30 2019 6:00 PM',
    OloID:'7734hdshfs874w',
    PrimaryID:'7734hdshfs874w',
    SecondaryID:'7734hdshfs874w',
    TransactionID:'sabsds73y87y33u',
    FaceMatch:'Success',
    FaceMatchScore: '88%',
    Liveliness:'Success',
    LivelinessScore:'88%',
    Mode:'Online',
    Connection:'Connection ABC',
    Application:'Application ABC',
    Endpoint:'Endpoint Name',
    userName: 'Full Name 1',
    application: 'Time Clock',
    endpointName: 'Tablet 1',
    dateTime:'May 30 2019 6:00 PM',
    Location:'Milpitas, Bld 15',

  },
  {
    key: '2',
    userId: 2,
    faces: icon,
    PrimaryID:'7734hdshfs874w',
    userName: 'Full Name 2',
    application: 'Access',
    endpointName: 'Tablet 2',
    dateTime:'May 30 2019 6:00 PM',
    Location:'Milpitas, Bld 15',
  },
  {
    key: '3',
    userId: 3,
    faces: icon,
    PrimaryID:'7734hdshfs874w',
    userName: 'Full Name 3',
    application: 'Edge',
    endpointName: 'Tablet 3',
    dateTime:'May 30 2019 6:00 PM',
    Location:'Milpitas, Bld 15',
  },
  {
    key: '4',
    userId: 4,
    faces: icon,
    PrimaryID:'7734hdshfs874w',
    userName: 'Full Name 4',
    application: 'Time Clock',
    endpointName: 'Tablet 4',
    dateTime:'May 30 2019 6:00 PM',
    Location:'Milpitas, Bld 15',
  },
  {
    key: '5',
    userId: 5,
    faces: icon,
    PrimaryID:'7734hdshfs874w',
    userName: 'Full Name 5',
    application: 'Access',
    endpointName: 'Tablet 5',
    dateTime:'May 30 2019 6:00 PM',
    Location:'Milpitas, Bld 15',
  },
  {
    key: '6',
    userId: 6,
    faces: icon,
    PrimaryID:'7734hdshfs874w',
    userName: 'Full Name 6',
    application: 'Edge',
    endpointName: 'Tablet 6',
    dateTime:'May 30 2019 6:00 PM',
    Location:'Milpitas, Bld 15',
  },
  {
    key: '7',
    userId: 7,
    faces: icon,
    PrimaryID:'7734hdshfs874w',
    userName: 'Full Name 7',
    application: 'Time Clock',
    endpointName: 'Tablet 7',
    dateTime:'May 30 2019 6:00 PM',
    Location:'Milpitas, Bld 15',
  },
  {
    key: '8',
    userId: 8,
    faces: icon,
    PrimaryID:'7734hdshfs874w',
    userName: 'Full Name 8',
    application: 'Access',
    endpointName: 'Tablet 8',
    dateTime:'May 30 2019 6:00 PM',
    Location:'Milpitas, Bld 15',
  },
  {
    key: '9',
    userId: 9,
    faces: icon,
    PrimaryID:'7734hdshfs874w',
    userName: 'Full Name 9',
    application: 'Edge',
    endpointName: 'Tablet 9',
    dateTime:'May 30 2019 6:00 PM',
    Location:'Milpitas, Bld 15',
  },
  {
    key: '10',
    userId: 10,
    faces: icon,
    PrimaryID:'7734hdshfs874w',
    userName: 'Full Name 10',
    application: 'Access',
    endpointName: 'Tablet 10',
    dateTime:'May 30 2019 6:00 PM',
    Location:'Milpitas, Bld 15',
  },
  {
    key: '11',
    userId: 11,
    faces: icon,
    PrimaryID:'7734hdshfs874w',
    userName: 'Full Name 11',
    application: 'Edge',
    endpointName: 'Tablet 11',
    dateTime:'May 30 2019 6:00 PM',
    Location:'Milpitas, Bld 15',
  },
]

